import {
  collectPublicApiExportNames,
  diffPublicApiContract,
} from './api-contract-tools';

const publicApiEntry = 'projects/ng-magary/src/public-api.ts';

const expectedRootExports = [
  'AvatarClickEvent',
  'AvatarPayload',
  'AvatarShape',
  'AvatarSize',
  'BadgeSeverity',
  'BreadcrumbItem',
  'CarouselAutoplayDirection',
  'CarouselEffect',
  'CarouselIndicatorPosition',
  'CarouselIndicatorStyle',
  'CarouselItemContext',
  'CarouselNavPosition',
  'CarouselNavStyle',
  'CarouselOrientation',
  'CarouselPreloadStrategy',
  'CarouselResponsiveOptions',
  'CarouselSlideEvent',
  'DividerAlign',
  'DividerLayout',
  'DividerType',
  'GalleriaImageLoadEvent',
  'GalleriaItem',
  'GalleriaItemEvent',
  'GalleriaResponsiveOptions',
  'InputSize',
  'InputType',
  'InputVariant',
  'MAGARY_VERSION',
  'MagaryAccordion',
  'MagaryAccordionTab',
  'MagaryAccordionTabChangeEvent',
  'MagaryAvatar',
  'MagaryBreadcrumb',
  'MagaryButton',
  'MagaryCard',
  'MagaryCarousel',
  'MagaryCascadeSelect',
  'MagaryCheckbox',
  'MagaryConfirmDialog',
  'MagaryConfirmation',
  'MagaryConfirmationService',
  'MagaryContextMenu',
  'MagaryDataView',
  'MagaryDatePicker',
  'MagaryDialog',
  'MagaryDivider',
  'MagaryFieldset',
  'MagaryFieldsetToggleEvent',
  'MagaryGalleria',
  'MagaryGrid',
  'MagaryGridEvent',
  'MagaryGridItem',
  'MagaryGridLayoutItem',
  'MagaryImage',
  'MagaryInput',
  'MagaryInputNumber',
  'MagaryKanban',
  'MagaryKanbanColumn',
  'MagaryKanbanItem',
  'MagaryKanbanMoveEvent',
  'MagaryMegaMenu',
  'MagaryMenubar',
  'MagaryMessage',
  'MagaryOrderList',
  'MagaryOrganizationChart',
  'MagaryOverlayPanel',
  'MagaryPaginator',
  'MagaryPanelmenu',
  'MagaryPickList',
  'MagaryRadioButton',
  'MagaryRadioGroup',
  'MagaryRating',
  'MagarySegmented',
  'MagarySegmentedCompareWith',
  'MagarySegmentedOption',
  'MagarySegmentedValue',
  'MagarySelect',
  'MagarySelectCompareWith',
  'MagarySelectOption',
  'MagarySelectValue',
  'MagarySidebar',
  'MagarySkeleton',
  'MagarySlideMenu',
  'MagarySlider',
  'MagarySpeedDial',
  'MagarySplitButton',
  'MagarySteps',
  'MagarySwitch',
  'MagaryTab',
  'MagaryTable',
  'MagaryTableColumn',
  'MagaryTableSortOrder',
  'MagaryTableSortState',
  'MagaryTabs',
  'MagaryTag',
  'MagaryTemplate',
  'MagaryTextArea',
  'MagaryThemeService',
  'MagaryTieredMenu',
  'MagaryTimeline',
  'MagaryToast',
  'MagaryToastMessage',
  'MagaryToastService',
  'MagaryToolbar',
  'MagaryTooltip',
  'MagaryTree',
  'MagaryTreeNode',
  'MagaryTreeNodeDropEvent',
  'MagaryTreeNodeSelectionEvent',
  'MagaryTreeSelectionValue',
  'MagaryUpload',
  'MenuBadgeSeverity',
  'MenuItem',
  'MenuItemClickEvent',
  'MenuToggleEvent',
  'PaginatorState',
  'PanelMenuMode',
  'SegmentedObjectOption',
  'SidebarAvatarConfig',
  'SidebarAvatarType',
  'SidebarLayoutMode',
  'SidebarMenuEventSource',
  'SidebarMenuFilter',
  'SidebarMenuItemClickEvent',
  'SidebarMenuItemExpandEvent',
  'SidebarMenuToggleEvent',
  'SidebarSection',
  'SpeedDialItem',
  'StepsItem',
  'TagSeverity',
  'Theme',
  'UploadEvent',
];

describe('ng-magary public API contract', () => {
  it('freezes the root export surface as the approved whitelist', () => {
    expect(collectPublicApiExportNames(publicApiEntry)).toEqual(expectedRootExports);
  }, 30_000);

  it('reports added and removed exports against the stored baseline', () => {
    expect(
      diffPublicApiContract({
        baselineExports: ['MagaryButton', 'MagarySidebar'],
        currentExports: ['MagaryButton', 'MagaryToast'],
      }),
    ).toEqual({
      addedExports: ['MagaryToast'],
      removedExports: ['MagarySidebar'],
    });
  });
});
